### ISSUE TITLE
Include Content that Uses Broken Extensions?

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab-demo#10]
@jasongrout Since a number of the Lab extensions aren't working eg widgets and geojson, should we bother with including content that relies on those extensions?  For example the geojson of the museums in DC

**Comment by jasongrout** [comment]
I think we should pin the demo to versions that work, but make the demo flexible enough so that that content can be skipped if needed. This means the demo won't be updated as often as JLab (at least right now), but I think that's okay.

Widgets should work with JLab 0.24. I'm not sure about geojson.

**Comment by blink1073** [comment]
Geojson is not yet updated.  Agreed that ipywidgets and google-drive are the only two known extensions that are compatible with JupyterLab 0.24.

**Comment by jzf2101** [comment]
So we should keep the Geojson, bqplot, dask, and pythreejs content?

**Comment by blink1073** [comment]
I'd say keep the content, so that when they become compatible we have the files in place.
